package com.helptrickbd.myapplicationsomithierp.core.security

import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.activity.result.ActivityResultLauncher
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.gms.common.api.CommonStatusCodes

data class GoogleAuthResult(
    val account: GoogleSignInAccount? = null,
    val statusCode: Int? = null,
    val isCancelled: Boolean = false,
    val errorMessage: String? = null
)

object GoogleSignInHelper {
    private const val TAG = "GoogleSignInHelper"

    /**
     * Builds and returns a GoogleSignInClient configured to request email and profile.
     * If a Web Client ID is available in resources, it also requests the ID token.
     */
    fun getGoogleSignInClient(context: Context): GoogleSignInClient {
        val gsoBuilder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()

        // Safely inspect for default_web_client_id if generated by google-services plugin
        val webClientId = try {
            val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            if (resId != 0) context.getString(resId) else null
        } catch (e: Exception) {
            null
        }

        if (!webClientId.isNullOrBlank()) {
            gsoBuilder.requestIdToken(webClientId)
        }

        return GoogleSignIn.getClient(context, gsoBuilder.build())
    }

    /**
     * Resets the previous sign-in session first, which forces Google Play Services
     * to ALWAYS display the full account picker dialog listing ALL Gmail accounts
     * on the user's Android device.
     */
    fun launchSignIn(context: Context, launcher: ActivityResultLauncher<Intent>?) {
        val client = getGoogleSignInClient(context)
        client.signOut().addOnCompleteListener {
            try {
                if (launcher != null) {
                    launcher.launch(client.signInIntent)
                } else if (context is android.app.Activity) {
                    context.startActivityForResult(client.signInIntent, 9001)
                }
            } catch (e: Exception) {
                Log.e(TAG, "Failed to launch Google Sign-In intent", e)
            }
        }
    }

    /**
     * Parses the GoogleSignInAccount from the ActivityResult Intent with diagnostic error information.
     */
    fun parseResult(data: Intent?): GoogleAuthResult {
        if (data == null) {
            return GoogleAuthResult(isCancelled = true, errorMessage = "No result data returned")
        }
        return try {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            val account = task.getResult(ApiException::class.java)
            GoogleAuthResult(account = account)
        } catch (e: ApiException) {
            val code = e.statusCode
            Log.e(TAG, "Google sign in failed with status code: $code", e)
            val message = when (code) {
                CommonStatusCodes.DEVELOPER_ERROR ->
                    "Code 10 (DEVELOPER_ERROR): Firebase-এ SHA-1 ফিঙ্গারপ্রিন্ট যোগ করুন (Add SHA-1 in Firebase Console)"
                12500 ->
                    "Code 12500: Firebase Authentication-এ Google Sign-in সক্রিয় করুন (Enable Google Sign-in in Firebase)"
                12501, CommonStatusCodes.CANCELED ->
                    "সাইন-ইন বাতিল করা হয়েছে (Sign-in cancelled)"
                CommonStatusCodes.NETWORK_ERROR ->
                    "নেটওয়ার্ক সংযোগ সমস্যা (Network error, check connection)"
                else ->
                    "Google Sign-In failed (Code: $code)"
            }
            GoogleAuthResult(
                statusCode = code,
                isCancelled = (code == 12501 || code == CommonStatusCodes.CANCELED),
                errorMessage = message
            )
        } catch (e: Exception) {
            Log.e(TAG, "Unexpected error parsing Google sign in result", e)
            GoogleAuthResult(errorMessage = e.localizedMessage ?: "Unknown sign in error")
        }
    }
}
